module.exports = {
  customfield_10091: { header: "Calling Date", type: "date" },
  customfield_10093: { header: "Vendor", type: "multi" },
  customfield_10084: { header: "Courier Partner", type: "multi" },
  customfield_10094: { header: "Cost Price", type: "string" },
  customfield_10106: { header: "Delhivery Escalation Ticket #", type: "string" },
  customfield_10057: { header: "Payment Type", type: "single" },
  customfield_10095: { header: "Sport", type: "multi" },
  customfield_10089: { header: "Product Category", type: "multi" },
  customfield_10085: { header: "Date of Procurement", type: "date" },
  customfield_10080: { header: "Shipping Tracking Details", type: "url" },
  customfield_10086: { header: "Pickup Schedule Date", type: "date" },
  customfield_10087: { header: "Dispatch Date", type: "date" },
  customfield_10088: { header: "Delivery Date", type: "date" },
  customfield_10119: { header: "RTO Delivered Date", type: "date" },
  customfield_10120: { header: "Replacement Procured Date", type: "date" },
  customfield_10121: { header: "Replacement Dispatch Date", type: "date" },
  customfield_10123: { header: "Return Delivery Date", type: "date" },
  customfield_10122: { header: "Replacement Delivered Date", type: "date" },
  customfield_10156: { header: "Purchase Invoice Link", type: "url" },
};